#!/usr/bin/python3

from kivy.config import Config
Config.set('graphics', 'width', 1200)
Config.set('graphics', 'height', 800)
#Config.set('input', 'mouse', 'mouse,multitouch_on_demand')

import matplotlib.pyplot as plt
import re, sys

from kivy.app import App
from kivy.clock import Clock, mainthread
from kivy_garden.mapview import MapMarker, MapView
from kivy.garden.matplotlib.backend_kivyagg import FigureCanvasKivyAgg
from kivy.properties import ListProperty, NumericProperty

from Communication import Communicator
from speedmeter import SpeedMeter

import AlmaNavLayer

class KtsMeter(SpeedMeter):

    def value_str(self, n):
        return '%.1f' % (n / 2.0)

_heading = { 0: 'N', 90: 'E', 180: 'S', 270: 'W' }

class HeadingIndicator(SpeedMeter):
    def value_str(self, n):
        return _heading.get(n) or str(n)

_serial = sys.argv[1]

_100 = range(100)

_l = [
    (1.975363849732992,48.87794375473663),
    (1.975102689568917,48.8780274694703),
    (1.975353484818965,48.87803093815558),
    (1.975809665021118,48.87790650705719),
    (1.97670312231099,48.8776829288465),
    (1.977669886056208,48.87746875696516),
    (1.977430197980181,48.87711098266111),
]

def _rec(lon, lat, heading, targetHeading):
    return { 'point': (lon, lat), 'heading': heading, 'targetHeading': targetHeading }


class Figure(FigureCanvasKivyAgg):

    axis = ListProperty()
    x1 = NumericProperty(0)

    def __init__(self, axis=(), **kwargs):
        self.fig, self.host = plt.subplots()
        FigureCanvasKivyAgg.__init__(self, self.fig, **kwargs)

    def initialize(self, axis):
        self.fig.subplots_adjust(right=0.75)
        host = self.host
        host.grid(True)

        par1 = host.twinx()
        par2 = host.twinx()
        par2.spines['right'].set_position(('axes', 1.2))

        data = [0 for _ in range(100)]
        l = []

        support = (host, par1, par2)
        for a, s in zip(axis, support):
            data_ = data[:]
            data_[0] = a[2]
            line, = s.plot(_100, data_, a[3], label=a[0])
            s.set_ylabel(a[0])
            s.yaxis.label.set_color(line.get_color())
            l.append({ 'line': line, 'data': data_ })

        self.l = tuple(l)

    def update(self, t):
        for d, v in zip(self.l, t):
            data = d['data']
            data.pop(0)
            data.append(v)
            d['line'].set_ydata(data)
            self.draw()

class Figure2(FigureCanvasKivyAgg):

    def __init__(self, **kwargs):
        self.fig = plt.figure()
        FigureCanvasKivyAgg.__init__(self, self.fig, **kwargs)
        self.vl = []
        self.il = []

    def initialize(self, xmax, ymax, xlabel, ylabel):
        axes = self.fig.gca()
        axes.set_xlim(0, xmax)
        axes.set_ylim(0, ymax)
        axes.set_xlabel(xlabel)
        axes.set_ylabel(ylabel)
        axes.grid(True)
        self.axes = axes
        self.scatter = self.axes.scatter(self.vl, self.il, s=4)

    def update(self, v, i):
        n = 30
        self.vl = self.vl[-n:] + [v]
        self.il = self.il[-n:] + [i]
        self.scatter.set_offsets(tuple(zip(self.vl, self.il)))
        self.draw()

class FigureBar(FigureCanvasKivyAgg):

    def __init__(self, **kwargs):
        self.fig = plt.figure()
        FigureCanvasKivyAgg.__init__(self, self.fig, **kwargs)
        self.maxUp = 1
        self.minDown = -1
        n = self.n = 80
        self.up = [0] * n
        self.down = [0] * n

    def initialize(self):
        plt.figure(self.fig.number)
        _n = range(self.n)
        self.barUp = plt.bar(_n, self.up)
        self.fig.gca().grid(True)
        self.barDown = plt.bar(_n, self.down)

    def update(self, up, down):
        if up > self.maxUp:
            self.maxUp = up
            self.fig.gca().set_ylim(self.minDown - 3, self.maxUp + 3)
        self.up = self.up[1:]
        self.up.append(up)
        for r, v in zip(self.barUp, self.up):
            r.set_height(v)

        if down < self.minDown:
            self.minDown = down
            self.fig.gca().set_ylim(self.minDown - 3, self.maxUp + 3)
        self.down = self.down[1:]
        self.down.append(down)
        for r, v in zip(self.barDown, self.down):
            r.set_height(v)

        self.draw()

_telemetryRe = re.compile(
    '^(\d+)\s+'
    'V=(\d+)\s+\d+\s+I=(\d+)\s+\d+\s+P=(\d+)\s+MPPT=\d+\s+L=(\d+)\s+R=(\d+)\s+.*'
    '\sH=(\d+)\sMH=(\d+)\sTH=(\d+)\sWP=(\d+)'
    '\s+(-?\d+\.\d+) _(-?\d+\.\d+)\s.*v=(-?\d+) \\^=(-?\d+)'
)

print(sys.argv)

class AlmaConsole(App):

    def __init__(self):
        App.__init__(self)
        self.comm = Communicator(_serial, self.input)
        self.badFrame = 0
        self.stage2 = False
        self.lastClock = 0

        self.debugLat = 48.877964
        self.debugLon = 1.975428

        self.minLat = 100
        self.maxLat = -100
        self.minLon = 400
        self.maxLon = -400

        self.navLayer = AlmaNavLayer.AlmaNavLayer(_l)

    def init_axis(self):
        if self.stage2: return
        self.stage2 = True
        self.root.ids.graph_aiw.initialize(
            (('w', 0, 25, 'r-'), ('v', 0, 22, 'g-'), ('i', 0, 120, 'b-')))
        self.root.ids.graph_iv.initialize(25, 1.5, 'V', 'I')
        self.root.ids.graph_rssi.initialize()
        self.root.ids.graph_bp.initialize(800, 25, 'B', 'W')
        self.root.ids.map.add_layer(self.navLayer)
        #self.root.ids.map.add_marker(MapMarker(lon=1.975102689568917,lat=48.8780274694703))

    def set_budget(self, budget, motion):
        print('$$$$$$$$$$$$$$$$$$$$$$$')
        v = budget.get_value(motion.pos)
        if not v: return
        print('******', v, '*********')
        self.comm.write('set budget %d' % int(v * 100))
        ids = self.root.ids
        ids.motor_set.state = 'down'
        ids.motor_off.state = 'normal'
        ids.motor_auto.state = 'normal'

    def xprint(self, *args):
        # Ugly, but since MapView grap all touch_up events, we have to propagate "by hand"
        self.set_budget(self.root.ids.b, args[1])

    # Must be called in mainthread !
    def processCoord(self, lat, lon, th, h):
        map = self.root.ids.map
        if lat > 95: # no fix
            return
        
        self.navLayer.addPoint(lon, lat, th, h)
        orig = (self.minLat, self.maxLat, self.minLon, self.maxLon)
        if lat < self.minLat: self.minLat = lat
        if lat > self.maxLat: self.maxLat = lat
        if lon < self.minLon: self.minLon = lon
        if lon > self.maxLon: self.maxLon = lon
        new = (self.minLat, self.maxLat, self.minLon, self.maxLon)
        if new != orig:
            map.center_on((self.maxLat + self.minLat) / 2, (self.minLon + self.maxLon) / 2)
            viewport_bbox = map.get_bbox()
            if not viewport_bbox.collide(self.minLat, self.minLon) \
               or not viewport_bbox.collide(self.maxLat, self.maxLon):
                map.zoom -= 1

    @mainthread
    def input(self, *args):
        print(args[0])
        self.init_axis()
        m = _telemetryRe.match(args[0].decode('iso-8859-1'))
        if not m:
            print('*** bad frame')
            self.badFrame += 1
            return
        remoteClock, v, i, b, l, r, h, magneticHeading, th, wp, lat, lon, rssiUp, rssiDown = m.groups()

        v = float(v) / 10
        i = (float(i) - 2200) / 10
        #w = float(w) / 1000
        w = 0

        b = float(b)

        ids = self.root.ids
        ids.v.value = v
        ids.i.value = i / 10.0
        ids.b.value = b / 100
        ids.l.value = float(l) / 100
        ids.r.value = float(r) / 100
        ids.w.value = w
        ids.mh.value = int(magneticHeading) * 360.0 / 256

        remoteClock = int(remoteClock)
        if remoteClock == self.lastClock: return
        self.lastClock = remoteClock

        ids.graph_aiw.update((w, v, i))
        ids.graph_iv.update(v, i / 100.0)
        ids.graph_rssi.update(-int(rssiUp), int(rssiDown))
        ids.graph_bp.update(b, i /4.0)

        self.debugLat = float(lat)
        self.debugLon = float(lon)

        self.processCoord(self.debugLat, self.debugLon, float(th) * 360.0 / 256, float(h) * 360.0 / 256)

console = AlmaConsole()
console.run()
console.comm.destroy()
